# Generated by Neurodocker and Reproenv.

FROM freesurfer/synthstrip:1.6

ENV ANTSPATH="/opt/ants-2.4.3/" \
    PATH="/opt/ants-2.4.3:$PATH"

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           ca-certificates \
           curl \
           unzip \
    && echo "Downloading ANTs ..." \
    && curl -fsSL -o ants.zip https://github.com/ANTsX/ANTs/releases/download/v2.4.3/ants-2.4.3-centos7-X64-gcc.zip \
    && unzip ants.zip -d /opt \
    && mv /opt/ants-2.4.3/bin/* /opt/ants-2.4.3 \
    && rm ants.zip

COPY requirements.txt /home/requirements.txt
RUN apt-get install -y -q --no-install-recommends wget \
    && wget https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py && rm get-pip.py \
    && pip install -r /home/requirements.txt

COPY checkpoints /home/checkpoints
COPY templates /home/templates
COPY src /home/src

USER root

ENTRYPOINT [ "/usr/bin/python3", "/home/src/synthba.py", "-i", "/home/inputs", "-o", "/home/outputs", "-c", "/home/checkpoints"  ]